### ISSUE TITLE
Dash in beginning of value is parsed as option

### ISSUE THREAD

**Issue by evilmachina** [sgmonda/stdio#18]
node app.js --value '-1pXM_DZMg'

Unknown option: "-p".

**Comment by yetanotherusernamebecausegithubisbugged** [comment]
Probably this is just yet another BASH design flaw. For example:
```
mkdir -- -l
ls -l
ls '-l'
ls "-l"
ls -l "-l"
```
Although it is interesting if anything can be done to fix it.

**Comment by sgmonda** [comment]
This should be fixed in version 2.0.0
