### ISSUE TITLE
Only lower case in stdio.question

### ISSUE THREAD

**Issue by gpanneti** [sgmonda/stdio#21]
stdio.question puts the answer in lower case only. Why not allowing uppercase ?

**Comment by Fleker** [comment]
This caused a pretty major issue for me since I was using it to input a user's authorization code as part of an OAuth flow. As it was doing this conversion, I continually ran into obscure errors that weren't the result of OAuth but of this library.

**Comment by Fleker** [comment]
https://github.com/google/google-auth-library-nodejs/issues/379

**Comment by sgmonda** [comment]
This should be fixed in the 2.0.0 release.
